/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AccountRouteImport } from './routes/account'
import { Route as BuyerRouteImport } from './routes/buyer'
import { Route as CreatorRouteImport } from './routes/creator'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as InternalRouteImport } from './routes/internal'
import { Route as LoginRouteImport } from './routes/login'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as StudioRouteImport } from './routes/studio'
import { Route as VerifyEmailRouteImport } from './routes/verify-email'
import { Route as TitleIdRouteImport } from './routes/title.$id'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiRazorpayWebhookRouteImport } from './routes/api/razorpay/webhook'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const BuyerRoute = BuyerRouteImport.update({
  id: '/buyer',
  path: '/buyer',
  getParentRoute: () => rootRouteImport,
} as any)
const CreatorRoute = CreatorRouteImport.update({
  id: '/creator',
  path: '/creator',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const InternalRoute = InternalRouteImport.update({
  id: '/internal',
  path: '/internal',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const StudioRoute = StudioRouteImport.update({
  id: '/studio',
  path: '/studio',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyEmailRoute = VerifyEmailRouteImport.update({
  id: '/verify-email',
  path: '/verify-email',
  getParentRoute: () => rootRouteImport,
} as any)
const TitleIdRoute = TitleIdRouteImport.update({
  id: '/title/$id',
  path: '/title/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRazorpayWebhookRoute = ApiRazorpayWebhookRouteImport.update({
  id: '/api/razorpay/webhook',
  path: '/api/razorpay/webhook',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/buyer': typeof BuyerRoute
  '/creator': typeof CreatorRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/internal': typeof InternalRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/studio': typeof StudioRoute
  '/verify-email': typeof VerifyEmailRoute
  '/title/$id': typeof TitleIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/razorpay/webhook': typeof ApiRazorpayWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/buyer': typeof BuyerRoute
  '/creator': typeof CreatorRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/internal': typeof InternalRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/studio': typeof StudioRoute
  '/verify-email': typeof VerifyEmailRoute
  '/title/$id': typeof TitleIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/razorpay/webhook': typeof ApiRazorpayWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/buyer': typeof BuyerRoute
  '/creator': typeof CreatorRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/internal': typeof InternalRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/studio': typeof StudioRoute
  '/verify-email': typeof VerifyEmailRoute
  '/title/$id': typeof TitleIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/razorpay/webhook': typeof ApiRazorpayWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account'
    | '/buyer'
    | '/creator'
    | '/forgot-password'
    | '/internal'
    | '/login'
    | '/onboarding'
    | '/reset-password'
    | '/signup'
    | '/studio'
    | '/verify-email'
    | '/title/$id'
    | '/api/auth/$'
    | '/api/razorpay/webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/account'
    | '/buyer'
    | '/creator'
    | '/forgot-password'
    | '/internal'
    | '/login'
    | '/onboarding'
    | '/reset-password'
    | '/signup'
    | '/studio'
    | '/verify-email'
    | '/title/$id'
    | '/api/auth/$'
    | '/api/razorpay/webhook'
  id:
    | '__root__'
    | '/'
    | '/account'
    | '/buyer'
    | '/creator'
    | '/forgot-password'
    | '/internal'
    | '/login'
    | '/onboarding'
    | '/reset-password'
    | '/signup'
    | '/studio'
    | '/verify-email'
    | '/title/$id'
    | '/api/auth/$'
    | '/api/razorpay/webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountRoute: typeof AccountRoute
  BuyerRoute: typeof BuyerRoute
  CreatorRoute: typeof CreatorRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  InternalRoute: typeof InternalRoute
  LoginRoute: typeof LoginRoute
  OnboardingRoute: typeof OnboardingRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignupRoute: typeof SignupRoute
  StudioRoute: typeof StudioRoute
  VerifyEmailRoute: typeof VerifyEmailRoute
  TitleIdRoute: typeof TitleIdRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiRazorpayWebhookRoute: typeof ApiRazorpayWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/buyer': {
      id: '/buyer'
      path: '/buyer'
      fullPath: '/buyer'
      preLoaderRoute: typeof BuyerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/creator': {
      id: '/creator'
      path: '/creator'
      fullPath: '/creator'
      preLoaderRoute: typeof CreatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/internal': {
      id: '/internal'
      path: '/internal'
      fullPath: '/internal'
      preLoaderRoute: typeof InternalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/studio': {
      id: '/studio'
      path: '/studio'
      fullPath: '/studio'
      preLoaderRoute: typeof StudioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify-email': {
      id: '/verify-email'
      path: '/verify-email'
      fullPath: '/verify-email'
      preLoaderRoute: typeof VerifyEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/title/$id': {
      id: '/title/$id'
      path: '/title/$id'
      fullPath: '/title/$id'
      preLoaderRoute: typeof TitleIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/razorpay/webhook': {
      id: '/api/razorpay/webhook'
      path: '/api/razorpay/webhook'
      fullPath: '/api/razorpay/webhook'
      preLoaderRoute: typeof ApiRazorpayWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountRoute: AccountRoute,
  BuyerRoute: BuyerRoute,
  CreatorRoute: CreatorRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  InternalRoute: InternalRoute,
  LoginRoute: LoginRoute,
  OnboardingRoute: OnboardingRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignupRoute: SignupRoute,
  StudioRoute: StudioRoute,
  VerifyEmailRoute: VerifyEmailRoute,
  TitleIdRoute: TitleIdRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiRazorpayWebhookRoute: ApiRazorpayWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
